### ISSUE TITLE
Host system for containers still running Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by nutterthanos** [lxc/lxd-demo-server#20]
Hello I was wondering why the host system or host systems that run the containers still run on Ubuntu 16.04 LTS and not Ubuntu 18.04 LTS?

**Comment by stgraber** [comment]
Because it will take some time and effort to update the tooling to handle Ubuntu Core 18 rather than Ubuntu Core 16 and since 16.04 is supported for another two years, there's not really been any reason to upgrade. It's plausible that I'll just end up waiting for Core20 and update straight to 20.04.
